### ISSUE TITLE
LibVirt issue

### ISSUE THREAD

**Issue by lgmn0203** [mweisel/gcp-gns3server#2]
I'm having this issue when i run the ansible playbook, it gives me this output error when installing the virt_net dependencies, can someone help me?

TASK [add gns3 user to libvirt system group] ***************************************************************************************************************************
ok: [35.229.93.65]
TASK [get and install dependencies for virt_net ansible module] ********************************************************************************************************
fatal: [35.229.93.65]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "libvirt-python", "lxml"], "msg": "stdout: Collecting libvirt-python\n  Using c
ached https://files.pythonhosted.org/packages/cb/6e/72e1b6db7089068d3ef145e7af76bb9ffd94d20f3ed88e2ed66d6e0e4f8f/libvirt-python-6.0.0.tar.gz\n    Complete output from c
ommand python setup.py egg_info:\n    libvirt-python requires Python 3.x to build\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup
.py egg_info\" failed with error code 1 in /tmp/pip-build-zzz6L6/libvirt-python/\n"}
PLAY RECAP *************************************************************************************************************************************************************
35.229.93.65               : ok=40   changed=2    unreachable=0    failed=1    skipped=12   rescued=0    ignored=0
localhost                  : ok=8    changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
Playbook run took 0 days, 0 hours, 0 minutes, 59 seconds

Thanks,

**Comment by dawheela** [comment]
Hi @laurenzgmn 

I had the same issue as well. Hence, I adjusted the Ansible playbook accordingly to use Python 3 as default as it seems to be a requirement by libvirt-python. I was able to fully deploy the GNS3-VM in GCP afterwards. Please find below my changes.

[patch-python3.txt](https://github.com/mweisel/gcp-gns3server/files/4201441/patch-python3.txt)

**Comment by mweisel** [comment]
The project has been updated for Python 3.
