### ISSUE TITLE
"libvirt-python requires Python 3.x to build" Error

### ISSUE THREAD

**Issue by pkts** [mweisel/gcp-gns3server#3]
I am getting the following error. My configurations are all very close to the defaults.
The GNS3 VM is "ubuntu-minimal-1804-lts", the default.

TASK [get and install dependencies for virt_net ansible module] **********************************************************************************************
fatal: [35.189.7.185]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip2", "install", "libvirt-python", "lxml"], "msg": "stdout: Collecting libvirt-python\n  Using cached https://files.pythonhosted.org/packages/cb/6e/72e1b6db7089068d3ef145e7af76bb9ffd94d20f3ed88e2ed66d6e0e4f8f/libvirt-python-6.0.0.tar.gz\n    Complete output from command python setup.py egg_info:\n    libvirt-python requires Python 3.x to build\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-SH0JGc/libvirt-python/\n"}

As a work-around I have tried to install python-libvirt via apt-get on the GNS3 VM:
sudo apt-get install python-libvirt

Then in 'tasks/libvirt.yml' file I have commented out libvirt-python package installation
Then re-running the playbook completes.

Will find out soon if it works.

**Comment by mweisel** [comment]
The project has been updated for Python 3.
