### ISSUE TITLE
conflict with openvpn tun0

### ISSUE THREAD

**Issue by g-arjuna** [mweisel/gcp-gns3server#4]
I was using open vpn to dial into my gcp gns3 server. I had roled up a new server as per the latest guide using wireguard. Surprisingly the open vpn link still came up. I had to disable open vpn , but the handshakes were through but , ping failed through wireguard. 

Then i had to put down the tun0 interface in the server for my link to come up. Any suggestions ?

**Comment by mweisel** [comment]
Are you sure this is a **new** VM instance? Neither the Ubuntu image or the updated Ansible code makes reference to OpenVPN.

**Comment by g-arjuna** [comment]
Yeah I had completely deleted the previous vm instance , waited for
confirmation , and then spun up a new vm using your new code .

**Comment by mweisel** [comment]
You also need to delete the disk and OpenVPN firewall rule.
