### ISSUE TITLE
Please add the option to access the devices running in the GNS3 Server

### ISSUE THREAD

**Issue by kishorekannanbsc** [mweisel/gcp-gns3server#5]
The below video shows How To Connect Remote GNS3 Devices to Home PC/LAN (GNS3 Cloud Server)
https://www.youtube.com/watch?v=tqVFADVFPRQ&t=84s

**Comment by mweisel** [comment]
I have a blog post that covers this - [SSH local port forwarding with remote GNS3 server](https://binarynature.blogspot.com/2019/06/ssh-local-port-forwarding-remote-gns3-server.html)

**Comment by kishorekannanbsc** [comment]
Hi Mark, 

Thank You, the below commands worked for me

**To access the devices inside GNS3 Server**
Step 1 : Connect to the GCP running instance from GCP cloud shell
Step 2 : Switch to root using sudo su -
Step 3 : Add the below commands in the remote GNS3 Server
ip tuntap add name tap0 mode tap
ifconfig tap0 10.0.0.1/24 up
ip route add 10.0.0.0/16 via 10.0.0.2
Step 4 : In the local desktop end, in wg config add 10.0.0.0/16 in the allowed IPs list

**Comment by kishorekannanbsc** [comment]
Hi Mark,

Thank You for the support, the below commands worked for me

**To access the devices inside GNS3 Server**
Step 1 : Connect to the GCP running instance from GCP cloud shell
Step 2 : Switch to root using sudo su -
Step 3 : Add the below commands in the remote GNS3 Server
ip tuntap add name tap0 mode tap
ifconfig tap0 10.0.0.1/24 up
ip route add 10.0.0.0/16 via 10.0.0.2
Step 4 : In the local desktop end, in wg config add 10.0.0.0/16 in the allowed IPs list
